alter table product modify pname varchar2(50);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'SLBM', '한방에 끝나요  ~~ ' , 10000, 10, '../images/slbm.jpg', 10, 1 );
insert into product values(PRODUCT_PNO_SEQ.NEXTVAL,'HEAVEN','천국',100,20,'../images/heaven.jpg',1,1);
insert into product values(PRODUCT_PNO_SEQ.NEXTVAL,'HELL','지옥',10,20,'../images/hell.jpg',1,1);
insert into product values(PRODUCT_PNO_SEQ.NEXTVAL,'AMERICA','미국',10000000,10,'../images/america.jpg',2,1);
insert into product values(PRODUCT_PNO_SEQ.NEXTVAL,'TIGER','호랑이',10000,20,'../images/tiger.jpg',2,1);
INSERT INTO PRODUCT VALUES(PRODUCT_PNO_SEQ.NEXTVAL, 'SCULPTOR', '19~23세 , 여성 에게 인기 많은 상품', 170000, 10, '../images/SC21A1102IV.jpg', 10, 1);
INSERT INTO PRODUCT VALUES(PRODUCT_PNO_SEQ.NEXTVAL, 'FILA', ' 19~28세 , 여성 에게 인기 많은 상품', 100000, 10, '../images/2500FE2DJD6104XCRM.jpg', 10, 1);
INSERT INTO PRODUCT VALUES(PRODUCT_PNO_SEQ.NEXTVAL, 'LAFUDGESTORE ', '19~28세 , 남성 에게 인기 많은 상품', 100000, 10, '../images/f-784.jpg', 10, 1);
INSERT INTO PRODUCT VALUES(PRODUCT_PNO_SEQ.NEXTVAL, 'EIDER', '18세 이하 , 남성 에게 인기 많은 상품', 300000, 10, '../images/DMW21559W2.jpg', 10, 1);
INSERT INTO PRODUCT VALUES(PRODUCT_PNO_SEQ.NEXTVAL, 'CODEGRAPHY', '19~28세 , 남성 에게 인기 많은 상품 ', 100000, 10, '../images/CBAW9IH001LG.jpg', 10, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'VANS', '핫해요 핫해! 블랙:화이트', 69000, 20, '../images/vans.jpg', 10, 10 );
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'PUPYY', '완전 이쁜 댕댕이옷', 49000, 30, '../images/puppy.jpg', 20, 5 );
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'SAMSONITE', '곧 다가올 위드코로나~ 여행을 대비하세요!', 368000, 50, '../images/samsonite.jpg', 30, 6 );
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'DESIGN', '개발자도 디자인이 중요하다!', 15000, 10, '../images/design.jpg', 40, 4 );
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'GOLF', '해골 바가지 골프가방', 648000, 15, '../images/golf.jpg', 50, 5 );
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '고대이집트의역사', '태고부터 페르시아 정복까지', 26000, 0, '../images/aHistoryOfEgypt.jpg' , 10, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '좋은기업을넘어위대한기업으로', '20주년 에디션', 18000, 10, '../images/goodToGreat.jpg' , 10, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '스웨덴의 복지 오로라는 얼마나 밝은가?', '멘슈어 올슨', 12000, 0, '../images/orora.jpg' , 10, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '압축 고전 60권', '책알못들을 위한 최소한의 교양 수업', 15000, 10, '../images/book.jpg' , 10, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '프로그래밍언어도감', '프로그래밍언어의특징과역사', 16000, 10, '../images/programing.jpg' , 10, 1);
INSERT INTO PRODUCT VALUES(PRODUCT_PNO_SEQ.NEXTVAL, '헬스1', '맛있다1', 10000, 10, '../images/h1.png',10,1);
INSERT INTO PRODUCT VALUES(PRODUCT_PNO_SEQ.NEXTVAL, '헬스2', '맛있다2', 10000, 10, '../images/h2.png',10,1);
INSERT INTO PRODUCT VALUES(PRODUCT_PNO_SEQ.NEXTVAL, '헬스3', '맛있다3', 10000, 10, '../images/h3.png',10,1);
INSERT INTO PRODUCT VALUES(PRODUCT_PNO_SEQ.NEXTVAL, '헬스4', '맛있다4', 10000, 10, '../images/h4.png',10,1);
INSERT INTO PRODUCT VALUES(PRODUCT_PNO_SEQ.NEXTVAL, '헬스5', '맛있다5', 10000, 10, '../images/h5.png',10,1);
Insert into product Values (product_pno_seq.nextval, 'iceshoes', '안신은듯한 편안함 ' , '500000',90, '../images/shoes.jpg',1,1);
Insert into product Values (product_pno_seq.nextval, 'koreashoes', '초 경량 신발 ' , '900000',50, '../images/koreashoes.jpg',10,1);
Insert into product Values (product_pno_seq.nextval, 'god', '한국의 GOD' , '10000',10, '../images/god.jpg',10,1);
Insert into product Values (product_pno_seq.nextval, 'rainhat', '양손의 자유' , '30000',10, '../images/rainhat.jpg',30,1);
Insert into product Values (product_pno_seq.nextval, 'tigerpanties', '호랑이기운이 !!' , '300000',30, '../images/tigerpanties.jpg',50,1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '척 테일러 올스타 70', '컨버스', 85500, 15, '../images/chuck70.PNG',20, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'MR530UNX', '뉴발란스', 99000, 20, '../images/mr530unx.PNG',15, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '테일윈드79', '나이키', 87000, 30, '../images/tailwind79.PNG',13, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '올드스쿨', '반스', 89000, 30, '../images/oldskool.PNG',15, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '에어 맥스', '나이키', 119000, 25, '../images/airmax.PNG',30, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '락앤락', '밀폐용기/텀블러 냉동실부터 오븐까지 어디은 안심 용기', 8900, 20,  '../images/p1.jpg' , 1 , 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '크리넥스', '실크소프트 미용티슈 230매 실크간이 부드러운 크리넥스 티슈', 9810, 10,  '../images/p2.jpg' , 6 , 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '퍼실', '라번데 2.7L 드럼용 세제/청소용품', 12000, 0,   '../images/p3.jpg' , 1 , 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '메디안', '듀얼이팩션 칫솔 5입', 7900, 10,   '../images/p4.jpg' , 5 , 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '리템앨앤씨', '수납정리용품 소품정리함', 2360, 0,   '../images/p5.jpg' , 1 , 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '플리스', '플리스 셋업 특가', 50000, 40, '../images/fleece.jpg', 10, 1) ;
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '밥솥', '6인용 전기압력밥솥', 130000, 10, '../images/cuckoo.jpg', 2, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '신발', 'old skool 운동화', 25000, 10, '../images/vans.jpg', 5, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '청소기', '주문폭주 청소기', 40000, 10, '../images/cleaner.jpg', 1, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, '충전기', '초고속 무선충전 거치대', 33000, 10, '../images/charger.jpg', 20, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'SHAMPOO', '비듬타파', 10000, 10, '../IMAGES/PRODUCT1.JPG',10, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'SOAP', '세균타파', 9000, 15, '../IMAGES/PRODUCT2.JPG',10, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'DETERGENT', '뽀드득뽀득', 8000, 20, '../IMAGES/PRODUCT3.JPG',10, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'CLEANSING', '각질안녕', 20000, 15, '../IMAGES/PRODUCT4.JPG',10, 1);
INSERT INTO PRODUCT VALUES (PRODUCT_PNO_SEQ.NEXTVAL, 'BODYWASH', '향수같은 바디워시', 20000, 20, '../IMAGES/PRODUCT5.JPG',10, 1);

